name: hungth_action

on:
  push:
    branches:
      - main

jobs:
  building:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      # Set up Docker
      - name: check Docker
        run: |
          docker --version

      # Build Docker image
      - name: Build Docker image
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo -S docker build -t hungth_connectdb:1.0.4 .

  deploy:
    runs-on: self-hosted
    needs: building

    steps:

    # - name: Pull Docker image from DockerHub on remote server
    #   run: |
    #     ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jarvis@172.16.1.242 \
    #     "cd /minvoice/apps/watchdog-invoice && echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hungth_connectdb:1.0.4"

    - name: Run Docker container on server
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jarvis@172.16.1.242 \
        "cd /minvoice/apps/watchdog-invoice && echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker run -d --name hungth-dbconnect hungth_connectdb:1.0.4"