name: hungth_action

on:
  push:
    branches:
      - main

jobs:
  building:
    runs-on: ubuntu-lastest

    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      # Set up Docker
      - name: check Docker
        run: |
          docker --version

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t hungth_connectdb:1.0.4 .

      # Push Docker image to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: |
          docker tag hungth_connectdb:1.0.4 ${{ secrets.DOCKERHUB_USERNAME }}/hungth_connectdb:1.0.4
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hungth_connectdb:1.0.4

  deploy:
    runs-on: self-hosted
    needs: building

    steps:  
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Pull Docker image from DockerHub on remote server
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jarvis@172.16.1.242 \
        "cd /minvoice/apps/watchdog-invoice && docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hungth_connectdb:1.0.4"

    - name: Run Docker container on remote server
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jarvis@172.16.1.242 \
        "cd /minvoice/apps/watchdog-invoice && docker run -d --name hungth-dbconnect ${{ secrets.DOCKERHUB_USERNAME }}/hungth_connectdb:1.0.4"
