name: hungth_action

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  building:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      # Set up Docker
      - name: Check Docker
        run: |
          docker --version

      # Read and increment version number
      - name: Get Current Version
        id: versioning
        run: |
          VERSION=$(cat version.txt)
          IFS='.' read -ra ADDR <<< "$VERSION"
          MAJOR=${ADDR[0]}
          MINOR=${ADDR[1]}
          PATCH=${ADDR[2]}
          PATCH=$((PATCH+1))  # Increment the PATCH version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "$NEW_VERSION" > version.txt  # Save the new version back to version.txt
          echo "::set-output name=new_version::$NEW_VERSION"  # Output the new version

      # Build Docker image with incremented version
      - name: Build image
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker build -t hungth_connectdb:${{ steps.versioning.outputs.new_version }} .
          
      - name: Print IMAGE_VERSION
        run: echo "IMAGE_VERSION=${{ steps.versioning.outputs.new_version }}"

      - name: Push new version to repo
        run: |
          git config --global user.name "haihunggg"
          git config --global user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Update version.txt to version ${{ steps.versioning.outputs.new_version }}"
          git push origin HEAD:main

  deploy:
    runs-on: self-hosted
    needs: building

    steps:

    - name: Off service 
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jarvis@172.16.1.242 \
        "cd /home/jarvis/minvoice/apps/watchdog-invoice/ && echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker compose down"

    - name: Print IMAGE_VERSION from building job
      run: echo "IMAGE_VERSION=${{ needs.building.outputs.new_version }}"

    - name: Update image version and restart service
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jarvis@172.16.1.242 \
          cd /home/jarvis/minvoice/apps/watchdog-invoice/ &&
          echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S sed -i 's/hungth_connectdb:[0-9.]\+/hungth_connectdb:${{ needs.building.outputs.new_version }}/g' docker-compose.yml
          echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker-compose up -d
