name: hungth_action

on:
  push:
    branches:
      - main

jobs:
  building:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      # Set up Docker
      - name: Check Docker
        run: |
          docker --version

      # Read and increment version number
      - name: Get Current Version
        id: versioning
        run: |
          VERSION=$(cat version.txt)
          IFS='.' read -ra ADDR <<< "$VERSION"
          MAJOR=${ADDR[0]}
          MINOR=${ADDR[1]}
          PATCH=${ADDR[2]}
          PATCH=$((PATCH+1))  # Increment the PATCH version
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "$NEW_VERSION" > version.txt  # Save the new version back to version.txt
          echo "IMAGE_VERSION=$NEW_VERSION" >> $GITHUB_ENV  # Pass the version to environment

      # Build Docker image with incremented version
      - name: Build image
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker build -t hungth_connectdb:${{ env.IMAGE_VERSION }} .

      - name: push new version to repo
        run: |
          git config user.name "haihunggg"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Bump version to ${{ env.IMAGE_VERSION }}"
          git push

  deploy:
    runs-on: self-hosted
    needs: building

    steps:

    # - name: Pull Docker image from DockerHub on remote server
    #   run: |
    #     ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jarvis@172.16.1.242 \
    #     "cd /minvoice/apps/watchdog-invoice && echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hungth_connectdb:1.0.4"

    - name: Run container on server
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no jarvis@172.16.1.242 \
        "echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker run -d --name hungth-dbconnect hungth_connectdb:${{ env.IMAGE_VERSION }}"
      
